# Imagen base
FROM python:3.12-slim

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Instalar dependencias
RUN pip install flask

# Copiar el código fuente
COPY app.py .

# Puerto que utilizará la aplicación
EXPOSE 5000

# Comando que se ejecutará al iniciar el contenedor
CMD ["python", "app.py"]